-- USAR O BANCO DE DADOS T_RENTAL
USE T_Rental;
GO

-- MOSTRAR TODAS AS TABELAS
SELECT * FROM ALUGUEL;
GO
SELECT * FROM CLIENTE;
GO
SELECT * FROM EMPRESA;
GO
SELECT * FROM MARCA;
GO
SELECT * FROM MODELO;
GO
SELECT * FROM VEICULO;
GO