CREATE DATABASE ROMAN_TARDE;
GO

USE ROMAN_TARDE;
GO

CREATE TABLE TIPOUSUARIO (

	idTipoUsuario TINYINT PRIMARY KEY IDENTITY,
	descricaoTipoUsuario VARCHAR(50) NOT NULL UNIQUE

);
GO

CREATE TABLE USUARIO (

	idUsuario INT PRIMARY KEY IDENTITY,
	idTipoUsuario TINYINT FOREIGN KEY REFERENCES TIPOUSUARIO(idTipoUsuario),
	email VARCHAR(300) UNIQUE NOT NULL,
	senha VARCHAR(16) NOT NULL CHECK(len(senha) >= 6)

);
GO

CREATE TABLE PROFESSOR (

	idProfessor SMALLINT PRIMARY KEY IDENTITY(1,1),
	idUsuario INT FOREIGN KEY REFERENCES USUARIO(idUsuario),
	nomeProfessor VARCHAR(30) NOT NULL,
	sobrenomeProfessor VARCHAR(40) NOT NULL

);
GO

CREATE TABLE TEMA (

	idTema SMALLINT PRIMARY KEY IDENTITY(1,1),
	nomeTema VARCHAR(30) NOT NULL UNIQUE

);

CREATE TABLE PROJETO (

	idProjeto INT PRIMARY KEY IDENTITY(1,1),
	idProfessor SMALLINT NOT NULL FOREIGN KEY REFERENCES PROFESSOR(idProfessor),
	idTema SMALLINT FOREIGN KEY REFERENCES TEMA(idTema),
	nomeProjeto VARCHAR(150) NOT NULL

);

CREATE TABLE imagemUsuario (

	idImagem INT PRIMARY KEY identity(1,1),
	idUsuario INT NOT NULL UNIQUE FOREIGN KEY REFERENCES usuario(idUsuario),
	binario VARBINARY(MAX) NOT NULL,
	mimeType VARCHAR(30) NOT NULL,
	nomeArquivo VARCHAR(250) NOT NULL,
	data_inclusao DATETIME DEFAULT GETDATE() NULL
);
GO